// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    // `npx prisma db seed` menjalankan seed DATA DEMO (tidak menyentuh
    // SUPER_ADMIN / tenant lain). Untuk akun dasar saja, pakai `npm run db:seed`.
    seed: "tsx prisma/seed-demo.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
  },
});
